my_age=14
ded_age=37
mom_age=39
mybrother_age=11
myseqondbrother_age=10
mysister_age=18
myseqondsister_age=8
print(my_age+5)
print(ded_age+5)
print(mom_age+5)
print(mybrother_age+5)
print(myseqondbrother_age+5)
print(mysister_age+5)
print(myseqondsister_age+5)